### ISSUE TITLE
Suggestions for next version

### ISSUE THREAD

**Issue by kartguru** [vvasiloud/AutoRelatedProducts-Magento2#1]
Hi Vvasiloud

Great work. Simple and does the trick. 

I thought that if you could exclude the current product from the related products feed it would be perfect.

btw, I found the `composer require vvasiloud/autorelatedproducts` command didn't work for me. Couldn't find the extension.

- michael

**Comment by vvasiloud** [comment]
Hello,

I am glad that you liked the extension. As for the composer I didn't set it up property so that's the reason isn't working. I will fix this when I will have the time to look into it.

I will look into it for removing the current product (probably it's a single like of code) but I not sure when I will have the time to do it because I moved away from Magento development for now. If you manage to do it yourself in the meanwhile feel free to do a pull request :).

Cheers.
